const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('api', {
  openPath:           (url)    => ipcRenderer.invoke('open-url', url),
  getFilePath:        (file)   => webUtils.getPathForFile(file),
  googleAuthStart:    (params) => ipcRenderer.invoke('google-auth-start', params),
  quitApp:            ()       => ipcRenderer.invoke('quit-app'),
  statPath:           (p)      => ipcRenderer.invoke('stat-path', p),
  getAuthStatus:      ()       => ipcRenderer.invoke('get-auth-status'),
  getCalendarEvents:  (params) => ipcRenderer.invoke('get-calendar-events', params),
  googleDisconnect:     ()                  => ipcRenderer.invoke('google-disconnect'),
  createCalendarEvent:  (ev)               => ipcRenderer.invoke('create-calendar-event', ev),
  updateCalendarEvent:  (eventId, evData)  => ipcRenderer.invoke('update-calendar-event', { eventId, eventData: evData }),
  deleteCalendarEvent:  (eventId)          => ipcRenderer.invoke('delete-calendar-event', eventId),
  listDriveImages:      (folderId)                       => ipcRenderer.invoke('list-drive-images', folderId),
  listDriveFolder:      (folderId)                       => ipcRenderer.invoke('list-drive-folder', folderId),
  getDriveImageData:    (fileId)                         => ipcRenderer.invoke('get-drive-image-data', fileId),
  driveTrashFile:       (fileId)                         => ipcRenderer.invoke('drive-trash-file', fileId),
  driveMoveFile:        (fileId, newParentId, oldParentId) => ipcRenderer.invoke('drive-move-file', fileId, newParentId, oldParentId),
  driveDownloadFile:    (fileId, fileName, mimeType, destPath) => ipcRenderer.invoke('drive-download-file', fileId, fileName, mimeType, destPath),
  selectDownloadFolder: ()                               => ipcRenderer.invoke('select-download-folder'),
  onAuthUpdate:         (cb)              => ipcRenderer.on('auth-update', (_e, msg) => cb(msg)),
  getLoginItem:         ()               => ipcRenderer.invoke('get-login-item'),
  setLoginItem:         (enable)         => ipcRenderer.invoke('set-login-item', enable),
  onUpdateStatus:       (cb)            => ipcRenderer.on('update-status', (_e, info) => cb(info)),
  installUpdate:        ()              => ipcRenderer.invoke('install-update'),
  checkForUpdates:      ()              => ipcRenderer.invoke('check-for-updates'),
  getAppVersion:        ()              => ipcRenderer.invoke('get-app-version'),
  focusWindow:          ()              => ipcRenderer.invoke('focus-window'),
  minimizeWindow:       ()              => ipcRenderer.invoke('minimize-window'),
  startScreenCapture:   ()              => ipcRenderer.invoke('start-screen-capture'),
  onCaptureImageReady:  (cb)            => ipcRenderer.on('capture-image-ready', (_e, dataURL) => cb(dataURL)),
  tasksGetDefaultList:  ()                                  => ipcRenderer.invoke('tasks-get-default-list'),
  tasksListTasks:       (taskListId)                        => ipcRenderer.invoke('tasks-list-tasks', taskListId),
  tasksCreateTask:      (params)                            => ipcRenderer.invoke('tasks-create-task', params),
  tasksPatchTask:       (params)                            => ipcRenderer.invoke('tasks-patch-task', params),
  tasksDeleteTask:      (params)                            => ipcRenderer.invoke('tasks-delete-task', params),
});
